  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Group Velocity Controllers ---------------------------------------
  lwr_velvet_group_forward_vel_controller:
    type: velocity_controllers/JointGroupVelocityController
#    type: velocity_controllers/JointVelocityController
    joints:
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint
      - velvet_fingers_joint_1

  # HQP Velocity Controller ----------------------------------------
  lwr_velvet_hqp_vel_controller:
    type: hqp_controllers/HQPVelocityController
    joints:
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint
#      - velvet_fingers_joint_1






