  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Group Velocity Controllers ---------------------------------------
  lwr_velvet_group_forward_vel_controller:
    type: velocity_controllers/JointGroupVelocityController
#    type: velocity_controllers/JointVelocityController
    joints:
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint
      - velvet_fingers_joint_1

  # HQP Velocity Controller ----------------------------------------
  lwr_velvet_hqp_vel_controller:
    type: hqp_controllers/HQPVelocityController
    joints:
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint
#      - velvet_fingers_joint_1

  # HQP Effort Controller ----------------------------------------
  lwr_velvet_hqp_eff_controller:
    type: hqp_controllers/HQPEffortController
    joints:
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint
    pid_lwr_0_joint: {p: 25000,  i: 10, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
    pid_lwr_1_joint: {p: 22000,  i: 10, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
    pid_lwr_2_joint: {p: 15000,  i: 10, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
    pid_lwr_3_joint: {p: 15000,  i: 10, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
    pid_lwr_4_joint: {p: 9000,  i: 10, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
    pid_lwr_5_joint: {p: 4000,  i: 10, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
    pid_lwr_6_joint: {p: 1500,  i: 10, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}





