#lwr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Effort Position Controllers ---------------------------------------
  lwr_0_joint_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_0_joint
    pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_1_joint_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_1_joint
    pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_2_joint_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_2_joint
    pid: {p: 800.0, i: 10, d: 5.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_3_joint_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_3_joint
    pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_4_joint_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_4_joint
    pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_5_joint_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_5_joint
    pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_6_joint_effort_pos_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_6_joint
    pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

  # Effort Velocity Controllers ---------------------------------------
  lwr_0_joint_effort_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: lwr_0_joint
    pid: {p: 8000.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_1_joint_effort_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: lwr_1_joint
    pid: {p: 800.0, i: 1000, d: 100.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_2_joint_effort_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: lwr_2_joint
    pid: {p: 800.0, i: 10, d: 5.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_3_joint_effort_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: lwr_3_joint
    pid: {p: 800.0, i: 10, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_4_joint_effort_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: lwr_4_joint
    pid: {p: 300.0, i: 5, d: 10.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_5_joint_effort_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: lwr_5_joint
    pid: {p: 50.0, i: 1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

  lwr_6_joint_effort_vel_controller:
    type: effort_controllers/JointVelocityController
    joint: lwr_6_joint
    pid: {p: 10.0, i: 0.1, d: 1.0, i_clamp_min: -10000, i_clamp_max: 10000}

  # Forward Position Controllers ---------------------------------------
  lwr_0_joint_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: lwr_0_joint

  lwr_1_joint_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: lwr_1_joint

  lwr_2_joint_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: lwr_2_joint

  lwr_3_joint_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: lwr_3_joint

  lwr_4_joint_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: lwr_4_joint

  lwr_5_joint_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: lwr_5_joint

  lwr_6_joint_forward_pos_controller:
    type: position_controllers/JointPositionController
    joint: lwr_6_joint

  # Forward Velocity Controllers ---------------------------------------
  lwr_0_joint_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwr_0_joint

  lwr_1_joint_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwr_1_joint

  lwr_2_joint_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwr_2_joint

  lwr_3_joint_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwr_3_joint

  lwr_4_joint_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwr_4_joint

  lwr_5_joint_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwr_5_joint

  lwr_6_joint_forward_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: lwr_6_joint






